# Generated by Django 2.2.21 on 2021-11-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_document_elemt_detal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='nr_documnet',
            new_name='nr_document',
        ),
    ]
